#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8762/eureka
#    enabled: true


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka
    enabled: true
    register-with-eureka: true
    fetch-registry: true         

    
    
