server:
  port: 10007
  
spring:
  application:
    name: report-generator
    
invoice:
  logo:
    path: "/jasper/images/stackextend-logo.png"
  template:
    path: "/jasper/invoice_template.jrxml"
